# Setup
title:        Hosted by jekyll
tagline:      A responsive theme for your project on GitHub Pages
baseurl:      "https://yoga9518.github.io/jekyll/"
paginate:     1
locale:       "en"

# About/contact
author:
  name:       Yoga Setiawan
  url:        https://yoga9518.github.io/blog 

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown

theme: jekyll-theme-cayman