# Setup
title:        Project or Site name
tagline:      A responsive theme for your project on GitHub Pages
baseurl:      ""
paginate:     1
locale:       "en"

# About/contact
author:
  name:       Author name
  url:        https://yoga9518.github.io/blog 

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown
